repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [ python ]
      files: ^(src/|test/)
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      language: system
      types: [ python ]
      files: ^(src/|test/)
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]
      files: ^(src/|test/)
    - id: mypy
      name: mypy
      entry: mypy
      args:
        - "--ignore-missing-imports"
      language: system
      types: [ python ]
      files: ^(src/|test/)
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [ python ]
      files: ^(src/|test/)