[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ros_license_toolkit"
version = "2.0.3"
description = "Checks ROS packages for correct license declaration."
readme = "README.md"
authors = [
    {name = "Christian Henkel", email = "christian.henkel2@de.bosch.com"},
]
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Framework :: Robot Framework :: Tool",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["ros", "license", "toolkit", "oss", "packages"]
dependencies = [
    "gitpython==3.1.62",
    "rospkg==1.6.2",
    "scancode-toolkit==32.5.0",
    "requests==2.34.2",
    "python-Levenshtein==0.27.4",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "pycodestyle", "flake8", "mypy", "isort", "bumpver"]

[project.urls]
homepage = "https://github.com/boschresearch/ros_license_toolkit"
repository = "https://github.com/boschresearch/ros_license_toolkit"

[project.scripts]
ros_license_toolkit = "ros_license_toolkit.main:main"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.codespell]
ignore-words-list = 'assertIn'
