name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: py${{ matrix.python-version }} @ ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # versions updated according to
          # https://devguide.python.org/versions/
          # on 2026-09-07
          - python-version: "3.7"  # legacy ...
            os: "ubuntu-22.04"
          - python-version: "3.10"
            os: "ubuntu-22.04"
          - python-version: "3.11"
            os: "ubuntu-22.04"
          - python-version: "3.12"
            os: "ubuntu-22.04"
          - python-version: "3.13"
            os: "ubuntu-22.04"
          - python-version: "3.14"
            os: "ubuntu-24.04"
          - python-version: "3.15"
            os: "ubuntu-24.04"
          - python-version: "3.16"
            os: "ubuntu-24.04"
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          pip install --upgrade pip
      - name: Install packages
        run: |
          pip install .
      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
