name: "TODO to Issue"
on:
  push:
    branches: [ main ]
jobs:
    todo_to_issue:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v7"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v5"
